---
minVersion: "0.10.0"
github:
  owner: getsentry
  repo: rust-sourcemap
changelogPolicy: auto
statusProvider:
  name: github
preReleaseCommand: bash scripts/bump-version
targets:
  - name: crates
  - name: github
    includeNames: /none/ # HACK to avoid Zeus
