name: Weekly CI

on:
  schedule:
    - cron: "0 0 * * 1" # every monday at 00:00
  workflow_dispatch:

env:
  RUSTFLAGS: -Dwarnings

jobs:
  weekly-ci:
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly, beta]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          rustup toolchain install ${{ matrix.rust }} --profile minimal --component clippy --no-self-update
          rustup default ${{ matrix.rust }}

      - run: cargo clippy --all-features --workspace --tests --examples -- -D clippy::all

      - run: cargo test --workspace --all-features
